project:
  type: website

website:
  title: "eevamaria.fi"
  favicon: favicon.ico
  search: true
  navbar:
    right:
      - href: index.qmd
        text: Etusivu
      - cv.qmd
      - blogi.qmd
      - hinnasto.qmd
      - ajanvaraus.qmd
      - icon: instagram
        href: https://www.instagram.com/fysioterapeuttieevamaria
      - icon: facebook
        href: https://www.facebook.com/Fysioterapeuttieevamaria
  page-footer: 
    background: light
    border: false
    center: 
    - icon: instagram
      href: https://www.instagram.com/fysioterapeuttieevamaria
    - icon: facebook
      href: https://www.facebook.com/Fysioterapeuttieevamaria
    - icon: linkedin
      href: https://fi.linkedin.com/in/eeva-maria-halminen
    - icon: envelope
      href: mailto:fysioterapeutti.eevamaria@gmail.com

format:
  html:
    theme: [custom.scss, lux]
    css: styles.css
    toc: false
    search: true

editor: visual

